const parkedKeywords = [
    '/parking-lander/',
    '/domain/parking',
    'SIMILAR DOMAINS FOR SALE',
    'sedoparking.com/',
    'explorefreeresults.com/',
    'parklogic.com/',
    'parkingcrew.net/',
    'window.park',
    'this domain is registred at',
    'contact the domain owner',
    'domain is parked',
    'domain is currently parked',
    'this domain name is parked',
    'This domain name is for sale',
    'for sale domain',
    'bid on this domain name',
    'domain might be for sale',
    'site is parked',
    'domain for sale', 
    'domain may be for sale', 
    'this page is parked', 
    'buy this domain', 
    'this domain is for sale', 
    'this website is for sale',
    'is parked free',
    'get this domain',
    'Inquire about this domain'
]

const cPanelPageKeywords = [
    "If you are the owner of this website, please contact your hosting provider",
    "The IP address has changed",
    "The site may have moved to a different server",
    "There has been a server misconfiguration",
    "this domain may have changed recently",
]

const bodyTextKeywords = [
    '.php on line',
    'server error',
    'Check your PHP configuration',
    'CE NOM DE DOMAINE',            
    'Diese neue Domain',
    'site coming soon',
    'If you are the owner of this domain name',
    'This Page Is Under Construction',
    'Site Is Under Construction',
    'Site Is currently Under Construction',
    'Welcome to WordPress. This is your first post.',
    'down for maintenance',
    'Database Connection Failed',
    'Access denied',
    "This site is currently not active",
    'the domain has expired',
    'Index of /',
    "Directory Listing Denied",
    "THIS WEBSITE IS NEW",
    'CHECK BACK AGAIN SOON',
    'Launching Soon',
    'This site does not exist',
    "This probably isn't the place you were looking for",
    "We are no longer accepting new clients",
    'HTTP Status: 404',
]

const titleKeywords = [
    'error',
    'ICANN Verification Needed',
    'under construction',
    'server is down',
    'Apache2 Ubuntu Default Page',
    'Coming Soon',
    'online casinos',
    'not found',
    'no offers available',
    'domain expired',
    'welcome to nginx',
    'connection denied',
    "Google Sites: Sign-in",
    "Office360 Sign In",
    "Google Sign In",
    'Directory Listing',
    'Suspended',
    'Expired',
    'Site not found',
    'This is the default server vhost',
    'Access denied',
    'Index of /',
    'forbidden',
    'domain not valid',
    'We are currently working in this page',
    'InMotion Hosting',
    'IIS Windows Server',
    'Flash Intro Page',
    'Chrome Web Store'
]

module.exports = { 
    parkedKeywords, 
    cPanelPageKeywords,
    titleKeywords,
    bodyTextKeywords
}